// Generates a tiny Connect 4 opening book covering all positions
// reachable in ≤ MAX_PLY plies.  For each position, runs the bitboard
// solver at PER_POS_BUDGET_MS and stores (best column, score).
//
// Run with:  npx tsx scripts/genOpeningBook.ts
// Output:    src/components/connect4OpeningBook.ts

import * as fs from 'node:fs';
import {
  Position,
  solve,
  type TTEntry,
} from '../src/components/connect4Solver';

const MAX_PLY = 3;
const PER_POS_BUDGET_MS = 3000;

interface BookEntry {
  col: number;
  score: number;
  exhaustive: 0 | 1;
}

const book = new Map<number, BookEntry>();
const sharedTT = new Map<number, TTEntry>();

function explore(p: Position) {
  if (book.has(p.key())) return;

  const result = solve(p.clone(), PER_POS_BUDGET_MS, sharedTT);
  book.set(p.key(), {
    col: result.col,
    score: result.score,
    exhaustive: result.exhaustive ? 1 : 0,
  });

  if (book.size % 25 === 0 || p.moves >= MAX_PLY) {
    console.log(
      `  [${String(book.size).padStart(4)}] ply=${p.moves} key=${p.key()} → col=${result.col} score=${result.score} exh=${result.exhaustive}`,
    );
  }

  if (p.moves < MAX_PLY) {
    for (let c = 0; c < 7; c++) {
      if (p.canPlay(c)) {
        const next = p.clone();
        next.play(c);
        explore(next);
      }
    }
  }
}

console.log(`Generating opening book through ply ${MAX_PLY} ...`);
console.time('book generation');
explore(new Position());
console.timeEnd('book generation');
console.log(`Book has ${book.size} entries.`);

// Serialise as a flat number-array of [key, col, score, exhaustive] tuples.
// Compact in source, fast to materialise into a Map at module load.
const tuples: string[] = [];
for (const [k, v] of book) {
  tuples.push(`[${k},${v.col},${v.score},${v.exhaustive}]`);
}

const content = `// Auto-generated by scripts/genOpeningBook.ts.  Do not edit by hand.
//
// Each entry: [position-key, best-col, score, exhaustive(0|1)].
// position-key is Pons's \`current + mask\` bitboard hash; cf. Position.key().

const RAW: readonly (readonly number[])[] = [
${tuples.join(',\n')}
];

export interface BookEntry {
  col: number;
  score: number;
  exhaustive: boolean;
}

export const OPENING_BOOK: ReadonlyMap<number, BookEntry> = (() => {
  const m = new Map<number, BookEntry>();
  for (const [k, c, s, e] of RAW) {
    m.set(k, { col: c, score: s, exhaustive: e === 1 });
  }
  return m;
})();
`;

fs.writeFileSync(
  'src/components/connect4OpeningBook.ts',
  content,
);
console.log('Written src/components/connect4OpeningBook.ts');
